SOURCES=SSLAlert.java\
	SSLAlertException.java\
	SSLAlertX.java\
	SSLCaughtAlertException.java\
	SSLCertificate.java\
	SSLCertificateRequest.java\
	SSLCertificateVerify.java\
	SSLCipherState.java\
	SSLCipherSuite.java\
	SSLClientHello.java\
	SSLClientKeyExchange.java\
	SSLConn.java\
	SSLContext.java\
	SSLDHParams.java\
	SSLDHPrivateKey.java\
	SSLDebug.java\
	SSLEncoded.java\
	SSLException.java\
	SSLFinished.java\
	SSLHandshake.java\
	SSLHandshakeClient.java\
	SSLHandshakeHashes.java\
	SSLHandshakeHdr.java\
	SSLHandshakeServer.java\
	SSLHelloRequest.java\
	SSLInputStream.java\
	SSLMAC.java\
	SSLOutputStream.java\
	SSLPDU.java\
	SSLPRF.java\
	SSLRSAParams.java\
	SSLReHandshakeException.java\
	SSLRecord.java\
	SSLRecordReader.java\
	SSLServerHello.java\
	SSLServerHelloDone.java\
	SSLServerKeyExchange.java\
	SSLServerSocket.java\
	SSLSessionData.java\
	SSLSocket.java\
	SSLThrewAlertException.java\
	SSLopaque.java\
	SSLuint16.java\
	SSLuint24.java\
	SSLuint32.java\
	SSLuint8.java\
	SSLuintX.java\
	SSLv3CertificateVerify.java\
	SSLv3Finished.java\
	SSLv3MAC.java\
	SSLv3PRF.java\
	SSLvector.java\
	TLSCertificateVerify.java\
	TLSFinished.java\
	TLSMAC.java\
	TLSPRF.java

SUBDIRS=demo

J_FLAGS=
#
#---Machine generated rules
JFLAGS += 
all: done
sub: subdirs done

done: ${SOURCES}
	javac $?
	touch done

