SOURCES=Certificate.java\
	DistinguishedName.java\
	Extension.java\
	SSLContextInt.java\
	SSLPolicyInt.java\
	SSLSocketXInt.java

SUBDIRS=
J_FLAGS=
#
#---Machine generated rules
JFLAGS += 
all:
	make JAVAC=javac sub
sub: subdirs sources

sources:
	$(JAVAC) $(JFLAGS) Certificate.java DistinguishedName.java Extension.java SSLContextInt.java SSLPolicyInt.java SSLSocketXInt.java 

subdirs:


Certificate:
	javac $(JFLAGS) Certificate.java
DistinguishedName:
	javac $(JFLAGS) DistinguishedName.java
Extension:
	javac $(JFLAGS) Extension.java
SSLContextInt:
	javac $(JFLAGS) SSLContextInt.java
SSLPolicyInt:
	javac $(JFLAGS) SSLPolicyInt.java
SSLSocketXInt:
	javac $(JFLAGS) SSLSocketXInt.java
clean:
	rm -f *.class
