/*
 * Decompiled with CFR 0.152.
 */
package com.oscar.core;

import com.oscar.core.BaseConnection;
import com.oscar.core.BaseResultSet;
import com.oscar.core.Field;
import java.sql.ParameterMetaData;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;

public interface BaseStatement {
    public BaseResultSet createResultSet(Field[] var1, List var2, String var3, int var4, long var5, int var7) throws SQLException;

    public BaseResultSet createResultSet(Field[] var1, List var2, String var3, int var4, long var5) throws SQLException;

    public BaseConnection getDBConnection();

    public void addWarning(String var1, String var2) throws SQLException;

    public int getFetchSize() throws SQLException;

    public int getFetchDirection() throws SQLException;

    public int getMaxRows() throws SQLException;

    public ResultSet getResultSet() throws SQLException;

    public int getResultSetConcurrency() throws SQLException;

    public int getResultSetType() throws SQLException;

    public int getResultSetHoldability() throws SQLException;

    public boolean getResultSetCanUpdateable() throws SQLException;

    public void setResultSetCanUpdateable(boolean var1) throws SQLException;

    public String getCursorName();

    public void setParamInfor(Object[][] var1);

    public ParameterMetaData getParamInfo();

    public boolean useTid();

    public void setUseTid(boolean var1);

    public boolean isDDLSql();

    public void resetDDLSql(boolean var1);

    public int getAutoGeneratedInfo();

    public void importValues(List var1);

    public List getImportValues();

    public void setTransferRowCount(int var1);

    public int getTransferRowCount();

    public boolean isResultNeeded();

    public Object getPreparedInfo();

    public boolean isCursorUsed();

    public boolean isPrepareAndNotRealPrepare();

    public void setPrepareAndNotRealPrepare(boolean var1);

    public int getStatementType();

    public void setResultSet(BaseResultSet var1);

    public void setUpdateBatchSize(int var1);

    public Field[] getFields();

    public void setFields(Field[] var1);

    public int[] getHashColIds();

    public void setHashColIds(int[] var1);

    public int getBuckets();

    public void setBuckets(int var1);

    public void setPrint(boolean var1);

    public boolean isPrint();

    public String getSQL();

    public boolean isHaveFuncRetrun();

    public boolean isNotRealPrepare();

    public String generatedKeySqlTransform(String var1);
}

