SOURCES=ASCII_CharStream.java\
	ASNAny.java\
	ASNBitString.java\
	ASNBoolean.java\
	ASNInteger.java\
	ASNNull.java\
	ASNObject.java\
	ASNObjectIdentifier.java\
	ASNOctetString.java\
	ASNPrintableString.java\
	ASNSequence.java\
	ASNSequenceOf.java\
	ASNSet.java\
	ASNSetOf.java\
	ASNSpecification.java\
	ASNTaggedType.java\
	ASNTime.java\
	ASNType.java\
	ASNTypeAlias.java\
	JJTParserState.java\
	Node.java\
	PackageProperties.java\
	ParseException.java\
	Parser.java\
	ParserConstants.java\
	ParserTokenManager.java\
	ParserTreeConstants.java\
	ParserVisitor.java\
	SimpleNode.java\
	Tag.java\
	Token.java\
	TokenMgrError.java

SUBDIRS=
J_FLAGS=
#
#---Machine generated rules
JFLAGS += 
all:
	make JAVAC=javac sub
sub: subdirs sources

sources:
	$(JAVAC) $(JFLAGS) ASCII_CharStream.java ASNAny.java ASNBitString.java ASNBoolean.java ASNInteger.java ASNNull.java ASNObject.java ASNObjectIdentifier.java ASNOctetString.java ASNPrintableString.java ASNSequence.java ASNSequenceOf.java ASNSet.java ASNSetOf.java ASNSpecification.java ASNTaggedType.java ASNTime.java ASNType.java ASNTypeAlias.java JJTParserState.java Node.java PackageProperties.java ParseException.java Parser.java ParserConstants.java ParserTokenManager.java ParserTreeConstants.java ParserVisitor.java SimpleNode.java Tag.java Token.java TokenMgrError.java 

subdirs:


ASCII_CharStream:
	javac $(JFLAGS) ASCII_CharStream.java
ASNAny:
	javac $(JFLAGS) ASNAny.java
ASNBitString:
	javac $(JFLAGS) ASNBitString.java
ASNBoolean:
	javac $(JFLAGS) ASNBoolean.java
ASNInteger:
	javac $(JFLAGS) ASNInteger.java
ASNNull:
	javac $(JFLAGS) ASNNull.java
ASNObject:
	javac $(JFLAGS) ASNObject.java
ASNObjectIdentifier:
	javac $(JFLAGS) ASNObjectIdentifier.java
ASNOctetString:
	javac $(JFLAGS) ASNOctetString.java
ASNPrintableString:
	javac $(JFLAGS) ASNPrintableString.java
ASNSequence:
	javac $(JFLAGS) ASNSequence.java
ASNSequenceOf:
	javac $(JFLAGS) ASNSequenceOf.java
ASNSet:
	javac $(JFLAGS) ASNSet.java
ASNSetOf:
	javac $(JFLAGS) ASNSetOf.java
ASNSpecification:
	javac $(JFLAGS) ASNSpecification.java
ASNTaggedType:
	javac $(JFLAGS) ASNTaggedType.java
ASNTime:
	javac $(JFLAGS) ASNTime.java
ASNType:
	javac $(JFLAGS) ASNType.java
ASNTypeAlias:
	javac $(JFLAGS) ASNTypeAlias.java
JJTParserState:
	javac $(JFLAGS) JJTParserState.java
Node:
	javac $(JFLAGS) Node.java
PackageProperties:
	javac $(JFLAGS) PackageProperties.java
ParseException:
	javac $(JFLAGS) ParseException.java
Parser:
	javac $(JFLAGS) Parser.java
ParserConstants:
	javac $(JFLAGS) ParserConstants.java
ParserTokenManager:
	javac $(JFLAGS) ParserTokenManager.java
ParserTreeConstants:
	javac $(JFLAGS) ParserTreeConstants.java
ParserVisitor:
	javac $(JFLAGS) ParserVisitor.java
SimpleNode:
	javac $(JFLAGS) SimpleNode.java
Tag:
	javac $(JFLAGS) Tag.java
Token:
	javac $(JFLAGS) Token.java
TokenMgrError:
	javac $(JFLAGS) TokenMgrError.java
clean:
	rm -f *.class
