SOURCES=BaseDSAPrivateKey.java\
	BaseDSAPublicKey.java\
	Blindable.java\
	EAYEncryptedPrivateKey.java\
	HMACInputStream.java\
	HMACOutputStream.java\
	PEMData.java\
	PKCS1Pad.java\
	RandomStore.java\
	RawDSAParams.java\
	RawDSAPublicKey.java

SUBDIRS=
J_FLAGS=
#
#---Machine generated rules
JFLAGS += 
all:
	make JAVAC=javac sub
sub: subdirs sources

sources:
	$(JAVAC) $(JFLAGS) BaseDSAPrivateKey.java BaseDSAPublicKey.java Blindable.java EAYEncryptedPrivateKey.java HMACInputStream.java HMACOutputStream.java PEMData.java PKCS1Pad.java RandomStore.java RawDSAParams.java RawDSAPublicKey.java 

subdirs:


BaseDSAPrivateKey:
	javac $(JFLAGS) BaseDSAPrivateKey.java
BaseDSAPublicKey:
	javac $(JFLAGS) BaseDSAPublicKey.java
Blindable:
	javac $(JFLAGS) Blindable.java
EAYEncryptedPrivateKey:
	javac $(JFLAGS) EAYEncryptedPrivateKey.java
HMACInputStream:
	javac $(JFLAGS) HMACInputStream.java
HMACOutputStream:
	javac $(JFLAGS) HMACOutputStream.java
PEMData:
	javac $(JFLAGS) PEMData.java
PKCS1Pad:
	javac $(JFLAGS) PKCS1Pad.java
RandomStore:
	javac $(JFLAGS) RandomStore.java
RawDSAParams:
	javac $(JFLAGS) RawDSAParams.java
RawDSAPublicKey:
	javac $(JFLAGS) RawDSAPublicKey.java
clean:
	rm -f *.class
