SOURCES=Bench.java\
	RFC822Hdr.java\
	Silo.java\
	Util.java

SUBDIRS=
J_FLAGS=
#
#---Machine generated rules
JFLAGS += 
all:
	make JAVAC=javac sub
sub: subdirs sources

sources:
	$(JAVAC) $(JFLAGS) Bench.java RFC822Hdr.java Silo.java Util.java 

subdirs:


Bench:
	javac $(JFLAGS) Bench.java
RFC822Hdr:
	javac $(JFLAGS) RFC822Hdr.java
Silo:
	javac $(JFLAGS) Silo.java
Util:
	javac $(JFLAGS) Util.java
clean:
	rm -f *.class
