## $Log: encoding.properties,v $
## Revision 1.2  1998/12/22 21:27:52  raif
## *** empty log message ***
##
## Revision 1.1  1998/10/24 23:02:47  raif
## * original version.
##
##
## $Endlog$
#
# Copyright (c) 1997, 1998 Systemics Ltd on behalf of
# the Cryptix Development Team.  All rights reserved.

# ----------------------------------------------------------------------
# Default home directory of ASN.1 coders
# ----------------------------------------------------------------------
asn.1.encoding.home = cryptix.asn1.encoding


# ----------------------------------------------------------------------
# Tracing properties
# ----------------------------------------------------------------------
Trace.DER =             false
Trace.EncodingFactory = false


# ----------------------------------------------------------------------
# Debugging properties
#
# If the library is compiled with PackageProperties.GLOBAL_DEBUG set to
# false, debugging is always disabled, and these properties are ignored.
# Otherwise, the higher the debugging level, the more information is
# displayed.
#
# To set the default debugging level, use
#   Debug.Level.* = ...
# ----------------------------------------------------------------------
Debug.Level.* = 0

Debug.Level.DER =             9
Debug.Level.EncodingFactory = 9