SOURCES=BaseCoder.java\
	CoderOperations.java\
	DER.java\
	PackageProperties.java

SUBDIRS=
J_FLAGS=
#
#---Machine generated rules
JFLAGS += 
all:
	make JAVAC=javac sub
sub: subdirs sources

sources:
	$(JAVAC) $(JFLAGS) BaseCoder.java CoderOperations.java DER.java PackageProperties.java 

subdirs:


BaseCoder:
	javac $(JFLAGS) BaseCoder.java
CoderOperations:
	javac $(JFLAGS) CoderOperations.java
DER:
	javac $(JFLAGS) DER.java
PackageProperties:
	javac $(JFLAGS) PackageProperties.java
clean:
	rm -f *.class
