SOURCES=CertContext.java\
	CertRequest.java\
	CertVerify.java\
	CertificateDecodeException.java\
	CertificateException.java\
	CertificateVerifyException.java\
	DERUtils.java\
	EAYDSAPrivateKey.java\
	EAYRSAPrivateKey.java\
	Pickledx509.java\
	WrappedObject.java\
	X509BasicConstraintsExtension.java\
	X509Cert.java\
	X509DSAPublicKey.java\
	X509Ext.java\
	X509Name.java\
	X509RSAPrivateKey.java\
	X509RSAPublicKey.java\
	X509SubjectPublicKeyInfo.java

SUBDIRS=
J_FLAGS=
#
#---Machine generated rules
JFLAGS += 
all:
	make JAVAC=javac sub
sub: subdirs sources

sources:
	$(JAVAC) $(JFLAGS) CertContext.java CertRequest.java CertVerify.java CertificateDecodeException.java CertificateException.java CertificateVerifyException.java DERUtils.java EAYDSAPrivateKey.java EAYRSAPrivateKey.java Pickledx509.java WrappedObject.java X509BasicConstraintsExtension.java X509Cert.java X509DSAPublicKey.java X509Ext.java X509Name.java X509RSAPrivateKey.java X509RSAPublicKey.java X509SubjectPublicKeyInfo.java 

subdirs:


CertContext:
	javac $(JFLAGS) CertContext.java
CertRequest:
	javac $(JFLAGS) CertRequest.java
CertVerify:
	javac $(JFLAGS) CertVerify.java
CertificateDecodeException:
	javac $(JFLAGS) CertificateDecodeException.java
CertificateException:
	javac $(JFLAGS) CertificateException.java
CertificateVerifyException:
	javac $(JFLAGS) CertificateVerifyException.java
DERUtils:
	javac $(JFLAGS) DERUtils.java
EAYDSAPrivateKey:
	javac $(JFLAGS) EAYDSAPrivateKey.java
EAYRSAPrivateKey:
	javac $(JFLAGS) EAYRSAPrivateKey.java
Pickledx509:
	javac $(JFLAGS) Pickledx509.java
WrappedObject:
	javac $(JFLAGS) WrappedObject.java
X509BasicConstraintsExtension:
	javac $(JFLAGS) X509BasicConstraintsExtension.java
X509Cert:
	javac $(JFLAGS) X509Cert.java
X509DSAPublicKey:
	javac $(JFLAGS) X509DSAPublicKey.java
X509Ext:
	javac $(JFLAGS) X509Ext.java
X509Name:
	javac $(JFLAGS) X509Name.java
X509RSAPrivateKey:
	javac $(JFLAGS) X509RSAPrivateKey.java
X509RSAPublicKey:
	javac $(JFLAGS) X509RSAPublicKey.java
X509SubjectPublicKeyInfo:
	javac $(JFLAGS) X509SubjectPublicKeyInfo.java
clean:
	rm -f *.class
